services:
  # Serviço da sua aplicação
  app:
    build: . # Constrói a imagem a partir do Dockerfile no diretório atual
    container_name: imersao
    ports:
      - "8000:8000" # Mapeia a porta 3000 do contêiner para a porta 3000 do seu host
    volumes:
      - .:/app # Monta o código-fonte local dentro do contêiner para desenvolvimento